FROM node:8.5.0-alpine

RUN mkdir /src

COPY . /src/

# Change the ownership of files to node user
RUN chown -R node:node /src
USER node

# Install dependencies
RUN apk --no-cache add --virtual builds-deps build-base python
RUN npm install --quiet
RUN npm rebuild bcrypt --build-from-source
RUN npm cache verify

EXPOSE 3000

WORKDIR /src
